# Generated by Django 3.1.2 on 2020-10-12 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.DateField(auto_now_add=True)),
                ('address_line1', models.CharField(max_length=100)),
                ('address_line2', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=40)),
                ('telophone', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('portal_zip', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('country', models.CharField(choices=[('America', 'America'), ('Germany', 'Germany'), ('Australia', 'Australia'), ('France', 'France')], default='select', max_length=10)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TokenData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('user_type', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bidder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.DateField(auto_now_add=True)),
                ('address_line1', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=40)),
                ('telophone', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('portal_zip', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('country', models.CharField(choices=[('America', 'America'), ('Germany', 'Germany'), ('Australia', 'Australia'), ('France', 'France')], default='select', max_length=10)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
