# Generated by Django 3.1.2 on 2020-10-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidder',
            name='address_line2',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
